### PR TITLE
Don't have to wait for plugins to be enabled

### PR DESCRIPTION
**Pull request by HSGamer**
Since we register enchantments on `onEnable`, all plugins are already `loaded` and available for `getPlugins`.

### CODE REVIEW

**Comment by zivoric** [comment]
I was thinking that it should still wait until all the plugins are enabled before the enchantments are registered, because a plugin's implementation of the enchantments or EnchantmentPlugin interface may require the plugin (or another plugin) to be enabled first.

**Comment by HSGamer** [comment]
> I was thinking that it should still wait until all the plugins are enabled before the enchantments are registered, because a plugin's implementation of the enchantments or EnchantmentPlugin interface may require the plugin (or another plugin) to be enabled first.

That is already done on the `loading` state.
It's not a good idea to wait because that will make a conflict on custom items plugins (not recognizing the enchantment on enable).

**Comment by zivoric** [comment]
> > I was thinking that it should still wait until all the plugins are enabled before the enchantments are registered, because a plugin's implementation of the enchantments or EnchantmentPlugin interface may require the plugin (or another plugin) to be enabled first.
> 
> That is already done on the `loading` state. It's not a good idea to wait because that will make a conflict on custom items plugins (not recognizing the enchantment on enable).

I guess that makes sense. My only issue though is, if the addon plugin is disabled (or can't be enabled for whatever reason), the enchantments will still register, which doesn't really make sense to me.

**Comment by HSGamer** [comment]
> > > I was thinking that it should still wait until all the plugins are enabled before the enchantments are registered, because a plugin's implementation of the enchantments or EnchantmentPlugin interface may require the plugin (or another plugin) to be enabled first.
> > 
> > 
> > That is already done on the `loading` state. It's not a good idea to wait because that will make a conflict on custom items plugins (not recognizing the enchantment on enable).
> 
> I guess that makes sense. My only issue though is, if the addon plugin is disabled (or can't be enabled for whatever reason), the enchantments will still register, which doesn't really make sense to me.

That's an issue the addon need to solve, not our issue.

**Comment by zivoric** [comment]
How the developer implements their enchantments if up to them, so allowing the enchantments to register regardless of the plugin's state (enabled/disabled) may actually be useful (so enchantments don't disappear if the plugin is disabled). Merging this

**Pull request merged**
